### ISSUE TITLE
consider making the filter api consistent with the django queryset api

### ISSUE THREAD

**Issue by benkonrath** [Said007/iterable_orm#4]
This is nice library. Thanks for creating it and open-sourcing it on github.

I noticed that your filter api isn't always compatible with the django queryset filter api which is problematic for my use case. For instance, you use `value_in` where as the django queryset api uses just `in`.

interable_orm:
https://github.com/Said007/iterable_orm/blob/master/iterable_orm/query.py#L31

django:
https://docs.djangoproject.com/en/1.10/ref/models/querysets/#in

Is there a reason for this? Thanks in advance.

**Comment by said-ali** [comment]
Hi,

Good point I can add this in next release.
